wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.44.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725633038.532303
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 105
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 105
      3:
      - 23
      4: 3.11.7
      5: 0.16.3
      6: 4.44.1
      8:
      - 5
      13: linux-x86_64
